INSERT INTO GENRES(ID, NAME, SLUG) VALUES
(1,	'Animation', 'animation'),
(2,	'Comedy', 'comedy'),
(3,	'Family', 'family'),
(4,	'Adventure', 'adventure'),
(5,	'Fantasy', 'fantasy'),
(6,	'Romance', 'romance'),
(7,	'Drama', 'drama'),
(8,	'Action', 'action'),
(9,	'Crime', 'crime'),
(10, 'Thriller', 'thriller'),
(11, 'Horror', 'horror'),
(12, 'History', 'history'),
(13, 'Science Fiction', 'science-fiction'),
(14, 'Mystery', 'mystery'),
(15, 'War', 'war'),
(16, 'Foreign', 'foreign'),
(17, 'Music', 'music'),
(18, 'Documentary',	'documentary'),
(19, 'Western', 'western'),
(20, 'TV Movie', 'tv-movie')
;
